[book]
authors = ["OpenMLSys Contributors"]
language = "en"
src = "en_chapters"
title = "Machine Learning Systems: Design and Implementation"

[build]
build-dir = ".mdbook/book"
create-missing = false

[preprocessor.openmlsys]
command = "python3 tools/mdbook_preprocessor.py"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/openmlsys/openmlsys-zh"
preferred-dark-theme = "navy"
additional-css = ["theme/dark-mode-images.css"]
