[book]
authors = ["OpenMLSys Contributors"]
language = "zh-CN"
src = "../../zh_chapters"
title = "机器学习系统：设计和实现（第一版）"

[build]
build-dir = "../../../.mdbook-v1-zh/book"
create-missing = false

[preprocessor.openmlsys-zh]
command = "python3 ../../../tools/mdbook_zh_preprocessor.py"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/openmlsys/openmlsys-zh"
preferred-dark-theme = "navy"
additional-css = ["theme/dark-mode-images.css", "theme/version-selector.css"]
additional-js = ["theme/version-selector.js"]
